### ISSUE TITLE
Interpreter killed by `os.kill(<python-interpreter-pid>, signal.SIGKILL)`

### ISSUE THREAD

**Issue by Resuscitating** [dzshn/faultless#1]
The following kills the interpreter.
```py
ensnared@snare:~$ python3
Python 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from os import *
>>> from signal import *
>>> from faultless import *
>>> @faultless
... def f(mainpid = getpid()):
...     kill(mainpid, SIGKILL)
... 
>>> f()
Killed
ensnared@snare:~$ /usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 2 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
^C
ensnared@snare:~$ 
```

I don't know if this is intended behaviour, but I'm assuming that it's not, since your `README` says "Functions wrapped by faultless will be unable to crash the interpreter directly". A possible way to fix this would be to wrap functions like `kill` to behave differently when passed the pid of the main python process, throwing an exception rather than sending the signal.

-- From, Herald (she/her)

**Comment by dzshn** [comment]
Handling `SIGKILL` to the main process is out of scope. It's impossible to register a signal handler for it, as the kernel behaviour is to kill the process immediately.

> A possible way to fix this would be to wrap functions like kill to behave differently when passed the pid of the main python process, throwing an exception rather than sending the signal.

At that point:

```py
import os
import signal
from ctypes import CDLL
from ctypes.util import find_library

CDLL(find_library("c")).kill(os.getpid(), signal.SIGKILL)
# or even
CDLL(find_library("c")).syscall(62, os.getpid(), signal.SIGKILL)
```

:3 

I've updated the README to address this issue, thank you for the heads up!

**Comment by dzshn** [comment]
(Or.. one actual (scary) solution would be to `ptrace` the child process and stop `kill` syscalls to the current pid or any parent pid, but that just seems like way too much work to a limitation I think doesn't affect the usefulness of this project)

**Comment by Resuscitating** [comment]
> It's impossible to register a signal handler for it
I didn't mean to stop the killing by using signal handlers. What I meant is that you could stop it by hooking the call that raises the signal in the first place, and only ever raising the signal if it wouldn't kill the main process. The `ptrace` solution that you suggested would do something similar, except it'd be a lot less selective.

**Comment by Resuscitating** [comment]
Here's an idea that could help prevent such a killing. Why not `fork` twice? Something like this.
```py
main_pid = os.fork()
if main_pid:
    hidden_pid = os.fork()
    if hidden_pid:
        # first parent
        # the first parent can simply use waitpid to wait for the child to exit, and then query the status of the second parent to determine whether to exit or take over.
    else:
        # second parent, your normal handling, checking, etc goes here
else:
     # child, run function here
```
You can use the second parent as a "hidden backup" of the main process. If the first parent is killed, the second parent can take over. Otherwise, it can exit. With that, it becomes a little more involved to completely end the main process. It's certainly not impossible, but it's a bit harder.

**Comment by dzshn** [comment]
Forking twice wont work, as if the main process is killed all child processes are killed too. The following will exit immediately: 

```py
import os
import time

if main := os.fork():
    if os.fork():
        time.sleep(100)
        print("survived!")  # <- clueless (this will never run)
    else:
        time.sleep(100)
else:
    os.kill(main, 9)
```

(disowning also wont work, it's generally disallowed to do such thing from a fork)

**Comment by dzshn** [comment]
> As for the `find_library` solution, I am of the opinion that if a user is loading a library solely to kill the main process, they must _really_ want to kill the main process, at which point, why not let them?

I'd say the same with directly killing the main process :P (`c` is just the standard C library, which always exists on unix systems)

**Comment by Resuscitating** [comment]
> I'd say the same with directly killing the main process :P

Alright, yeah. That's fair lol. Thanks for taking the time to respond to me :)
